name: Build & Release Seamless Glance

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write

jobs:
  build-macos:
    name: Build macOS binaries
    runs-on: macos-latest

    strategy:
      matrix:
        target:
          - aarch64-apple-darwin
          - x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename binary
        run: |
          BIN=seamless-glance
          OUT=seamless-glance-${{ matrix.target }}
          mv target/${{ matrix.target }}/release/$BIN $OUT

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: seamless-glance-*


  build-linux:
    name: Build Linux binary
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Rename binary
        run: |
          BIN=seamless-glance
          OUT=seamless-glance-x86_64-unknown-linux-gnu
          mv target/x86_64-unknown-linux-gnu/release/$BIN $OUT

      - uses: actions/upload-artifact@v4
        with:
          name: linux
          path: seamless-glance-*

  release:
      name: Publish GitHub Release
      needs: [build-macos, build-linux]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4

        - uses: softprops/action-gh-release@v2
          with:
            prerelease: ${{ github.ref_name == 'dev' }}
            files: |
              **/seamless-glance-*
